### ISSUE TITLE
Test fails when executed from a generated project

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-incubator/apiserver-builder#290]
### Issue

Even if an etcd server is defined under the PATH of the user, then `go test` fails

```
$ export PATH=$PATH:./etcd-v3.3.10-darwin-amd64
$ etcd                                         
2018-12-14 09:56:10.303882 I | etcdmain: etcd Version: 3.3.10
2018-12-14 09:56:10.303993 I | etcdmain: Git SHA: 27fc7e2
2018-12-14 09:56:10.303998 I | etcdmain: Go Version: go1.10.4
2018-12-14 09:56:10.304004 I | etcdmain: Go OS/Arch: darwin/amd64
2018-12-14 09:56:10.304009 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2018-12-14 09:56:10.304015 N | etcdmain: failed to detect default host (default host not supported on darwin_amd64)
2018-12-14 09:56:10.304022 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2018-12-14 09:56:10.304108 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-12-14 09:56:10.304481 I | embed: listening for peers on http://localhost:2380
2018-12-14 09:56:10.304642 I | embed: listening for client requests on localhost:2379
2018-12-14 09:56:10.305818 I | etcdserver: name = default
2018-12-14 09:56:10.305831 I | etcdserver: data dir = default.etcd
2018-12-14 09:56:10.305836 I | etcdserver: member dir = default.etcd/member
2018-12-14 09:56:10.305841 I | etcdserver: heartbeat = 100ms
2018-12-14 09:56:10.305845 I | etcdserver: election = 1000ms
2018-12-14 09:56:10.305849 I | etcdserver: snapshot count = 100000
2018-12-14 09:56:10.305861 I | etcdserver: advertise client URLs = http://localhost:2379
2018-12-14 09:56:10.319368 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 6
2018-12-14 09:56:10.319463 I | raft: 8e9e05c52164694d became follower at term 3
2018-12-14 09:56:10.319482 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 3, commit: 6, applied: 0, lastindex: 6, lastterm: 3]
2018-12-14 09:56:10.321916 W | auth: simple token is not cryptographically signed
2018-12-14 09:56:10.322673 I | etcdserver: starting server... [version: 3.3.10, cluster version: to_be_decided]
2018-12-14 09:56:10.322788 E | etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on darwin)
2018-12-14 09:56:10.323283 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2018-12-14 09:56:10.323431 N | etcdserver/membership: set the initial cluster version to 3.3
2018-12-14 09:56:10.323494 I | etcdserver/api: enabled capabilities for version 3.3
2018-12-14 09:56:11.720234 I | raft: 8e9e05c52164694d is starting a new election at term 3
2018-12-14 09:56:11.720274 I | raft: 8e9e05c52164694d became candidate at term 4
2018-12-14 09:56:11.720299 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 4
2018-12-14 09:56:11.720320 I | raft: 8e9e05c52164694d became leader at term 4
2018-12-14 09:56:11.720337 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 4
2018-12-14 09:56:11.720711 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
2018-12-14 09:56:11.720803 I | embed: ready to serve client requests
2018-12-14 09:56:11.722034 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
^C2018-12-14 09:56:11.745957 N | pkg/osutil: received interrupt signal, shutting down...
2018-12-14 09:56:11.746108 I | etcdserver: skipped leadership transfer for single member cluster
```
### Error
```
go test ./pkg/...
?       github.com/cmoulliard/my-project/pkg    [no test files]
?       github.com/cmoulliard/my-project/pkg/apis       [no test files]
?       github.com/cmoulliard/my-project/pkg/apis/application   [no test files]
?       github.com/cmoulliard/my-project/pkg/apis/application/install   [no test files]
Running Suite: v1 Suite
=======================
Random Seed: 1544777741
Will run 1 of 1 specs

[::]:52298
[::]:52299
[::]:52300
panic: exec: "etcd": executable file not found in $PATH

goroutine 88 [running]:
github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test.(*TestEnvironment).startEtcd(0xc000589080, 0xc000048c00)
        /Users/dabou/Code/go-workspace/src/github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test/server.go:167 +0x47b
created by github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test.(*TestEnvironment).Start
        /Users/dabou/Code/go-workspace/src/github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test/server.go:85 +0xb5
FAIL    github.com/cmoulliard/my-project/pkg/apis/application/v1alpha1  0.090s
?       github.com/cmoulliard/my-project/pkg/client/clientset_generated/clientset       [no test files]
?       github.com/cmoulliard/my-project/pkg/client/clientset_generated/clientset/fake  [no test files]
?       github.com/cmoulliard/my-project/pkg/client/clientset_generated/clientset/scheme        [no test files]
?       github.com/cmoulliard/my-project/pkg/client/clientset_generated/clientset/typed/application/v1alpha1    [no test files]
?       github.com/cmoulliard/my-project/pkg/client/clientset_generated/clientset/typed/application/v1alpha1/fake       [no test files]
?       github.com/cmoulliard/my-project/pkg/client/informers_generated/externalversions        [no test files]
?       github.com/cmoulliard/my-project/pkg/client/informers_generated/externalversions/application    [no test files]
?       github.com/cmoulliard/my-project/pkg/client/informers_generated/externalversions/application/v1alpha1   [no test files]
?       github.com/cmoulliard/my-project/pkg/client/informers_generated/externalversions/internalinterfaces     [no test files]
?       github.com/cmoulliard/my-project/pkg/client/listers_generated/application/v1alpha1      [no test files]
?       github.com/cmoulliard/my-project/pkg/controller [no test files]
Running Suite: Component Suite
==============================
Random Seed: 1544777741
Will run 1 of 1 specs

[::]:52303
[::]:52304
[::]:52305
panic: exec: "etcd": executable file not found in $PATH

goroutine 84 [running]:
github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test.(*TestEnvironment).startEtcd(0xc0000b74a0, 0xc0000b87e0)
        /Users/dabou/Code/go-workspace/src/github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test/server.go:167 +0x47b
created by github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test.(*TestEnvironment).Start
        /Users/dabou/Code/go-workspace/src/github.com/cmoulliard/my-project/vendor/github.com/kubernetes-incubator/apiserver-builder/pkg/test/server.go:85 +0xb5
FAIL    github.com/cmoulliard/my-project/pkg/controller/component       0.090s
?       github.com/cmoulliard/my-project/pkg/controller/sharedinformers [no test files]
?       github.com/cmoulliard/my-project/pkg/openapi    [no test files]
```

**Comment by yue9944882** [comment]
> export PATH=$PATH:./etcd-v3.3.10-darwin-amd64
> panic: exec: "etcd": executable file not found in $PATH

@cmoulliard please install etcd into ur system PATH (instead of bash context PATH) or export etcd to ur PATH again before running go test

closing since that i suppose this issue is resolved. feel free to reopen anytime.

/triage support
/close
